export const surpriseMePrompts = [
    'A beautiful house in tropical modernism style inside of a forest and full of trees and plants ',
    'A ktm motorcycle in a narrow cyberpunk street, photography',
    '3D render of a floating futuristic castle in a clear sky, digital art',
    'Ultrawide, highway,  with golden ratio style, 4K , sides  are prairies, light is Golden hour, sky with red Clouds, ultrarealistic, CinémaScope, ultra wide format, ratio 16/9, 1/1000 sec, maximum resolution, Sharp details',
    'botticelli’s simonetta vespucci young portrait photography hyperrealistic modern dressed, futuristic',
    'a photo of cat flying out to space as an astronaut, digital art',
    'a medium-full-shot,movie poster studio photographic portrait of perfect beautiful Korean women wearing strapless and tiny short pant,outdoors,sunset photo at golden hours,depth of field,Bokeh,shot on Leica Q2,on Flickr',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'Synthwave halloween formula 1 car racing on a night road in Singapore',
    'realistic oil painting of zombies at the octoberfest in Munich, drinking beer, vomiting, dancing, yelling, ',
    'pink ape Astronaut in space holding a claymate in a photorealistic style, digital art',
    'a realistic photographic close up of a floating transparent cup of coffee with liquid splashing in zero gravity with light rays refracting through the coffee',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'painting of a young woman absorbed in thought, in pink mini dress, looking at her cellphone while wating at a bus stop, on an empty road, in Willem Maris impressionist style',
    'A photo of a white fur monster standing in a purple room',
    "a teenage girl of afghani descent with striking rainbow eyes stares at the camera with a deep read head scarf. kodachrome film",
    'A Samurai riding a Horse on Mars, lomography.',
    'A greeting cat, Vector Illustation, line stamp, kawaii',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'a spraypatined picture on a concrete wall of technicolor jesus fighting black and white satan',
    'A futuristic cyborg dance club, neon lights',
    'Wet chitinous texture, greasy --q 2 --s 12000',
    'A digital Illustration of the a purely mechanical television, 4k, detailed, fantasy vivid colors',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'orange looking like water-universe-Earth in the background is a dusty wooden desk, room interior, realistic, abstract art, cinematic bright lighting, colorful, foggy, smokes --ar 16:9',
    'Axel Auriant, ultra detail, ultra realist, 8K, 3D, natural light, photorealism',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'fibonacci, stone, snail, wallpaper, colorful, blue gray green, 3d pattern, 8k',
  ];